kind: Service
apiVersion: v1
metadata:
  name: "usserverproductionservice"
spec:
  selector:
    app: "usserverproduction"
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080         
  type: LoadBalancer